repos:
  - repo: local
    hooks:
      - id: check_duplicate_method_names
        name: Check Odoo class for duplicate methods using Python
        entry: python scripts/check_duplicate_method_names.py
        language: system
        types: [python]
        stages: [commit]

      - id: detect-raw-sql-delete-insert
        name: Detect raw SQL DELETE/INSERT
        entry: python scripts/check_sql.py
        language: system
        types: [python]
        stages: [commit]

      - id: class-property-checker
        name: Check for missing return in write(), copy(), create() or unlink() methods
        entry: python scripts/check_for_return.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-xml-header
        name: Check XML header
        entry: python scripts/check_xml_header.py
        language: system
        types: [xml]
        stages: [commit]

      - id: check-xml-closing-tags
        name: Check XML closing tags
        entry: python scripts/check_xml_closing_tags.py
        language: system
        types: [xml]
        stages: [commit]

      - id: check-report-template
        name: Check report template
        entry: python scripts/check_report_template.py
        language: system
        types: [xml]
        files: \.xml$
        stages: [commit]

      - id: check-compute-function
        name: Check Compute Function Exists
        entry: python scripts/check_compute_function.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-manifest-fields
        name: Check Odoo Manifest Fields in All __manifest__.py Files
        entry: python scripts/check_requirements.py
        language: system
        files: ^.*__manifest__.py$
        stages: [commit]

      - id: check-print-usage
        name: Check print() usage in Python files
        entry: python scripts/check_print_usage.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-duplicate-ids
        name: Check for duplicate IDs in XML files
        entry: python scripts/check_duplicate_ids.py
        language: system
        types: [xml]
        files: \.xml$
        stages: [commit]

      - id: check-sudo-comment
        name: Check .sudo() usage has inline comment
        entry: python scripts/check_sudo_comment.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-long-functions
        name: Check long Python functions
        entry: python scripts/check_long_functions.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-odoo-models-naming
        name: Check Odoo Models Naming
        entry: python scripts/check_module_names.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-module-prefix
        name: Ensure module folders in addons start with dc_ or modify_
        entry: python scripts/check_model_file.py
        language: system
        types: [python]
        stages: [commit]

      - id: check-xml-filenames
        name: Check XML filenames prefix
        entry: python scripts/check_xml_filenames.py
        language: system
        types: [xml]
        stages: [commit]

      - id: check-lines-max
        name: Check Python line length
        entry: python scripts/check_lines_max.py
        language: system
        types: [python]
        stages: [commit]
